# Other
set_center: true

# Image Format Control
Width: 2200
Height: 1740
OffsetX: 0
OffsetY: 22
PixelFormat: 0x01080009 # BayerRG 8: 0x01080009  |  Mono 8: 0x01080001
ImageCompressionMode: 2 # 0: OFF | 2: HB

# Acquisition Control
AcquisitionLineRate: 10
AcquisitionLineRateEnable: 1

TriggerMode: 1
TriggerSource: -1       # -1: Action1
TriggerActivation: 0

ExposureTime: 18000.0
ExposureAuto: 0
AutoExposureTimeLowerLimit: 5000
AutoExposureTimeUpperLimit: 45000

# Analog Control
Gain: 20.0
GainAuto: 2
AutoGainLowerLimit: 25
AutoGainUpperLimit: 10

Brightness: 100

# Digital IO Control
LineSelector: [0, 1]
LineMode: [0, 8]
LineDebouncerTime: [50, 50]
StrobeEnable: [0, 1]
LineSource: [0, 0]
StrobeLineDuration: [0, 0]
StrobeLineDelay: [0, 0]
StrobeLinePreDelay: [0, 0]

# Action Control
ActionDeviceKey: 0x00000001
ActionGroupMask: 0x00000001
ActionGroupKey: 0x00000001

# Transport Layer Control
GevIEEE1588: 1