#ifndef _HIKCAM_PARAM_CFG_H_
#define _HIKCAM_PARAM_CFG_H_

/*Image Format Control*/
typedef enum _HIK_PIXEL_FORMAT_ // PixelFormat
{
    HIK_PIXEL_FORMAT_Mono8 = 0x01080001,
    HIK_PIXEL_FORMAT_Mono10 = 0x01100003,
    HIK_PIXEL_FORMAT_Mono10Packed = 0x010C0004,
    HIK_PIXEL_FORMAT_Mono12 = 0x01100005,
    HIK_PIXEL_FORMAT_Mono12Packed = 0x010C0006, 
    HIK_PIXEL_FORMAT_Mono16 = 0x01100007,
    HIK_PIXEL_FORMAT_RGB8Packed = 0x02180014,
    HIK_PIXEL_FORMAT_YUV422_8 = 0x02100032,
    HIK_PIXEL_FORMAT_YUV422_8_UYVY = 0x0210001F,
    HIK_PIXEL_FORMAT_BayerGR8 = 0x01080008,
    HIK_PIXEL_FORMAT_BayerRG8 = 0x01080009,
    HIK_PIXEL_FORMAT_BayerGB8 = 0x0108000A,
    HIK_PIXEL_FORMAT_BayerBG8 = 0x0108000B,
    HIK_PIXEL_FORMAT_BayerGB10 = 0x0110000e,
    HIK_PIXEL_FORMAT_BayerGB12 = 0x01100012, 
    HIK_PIXEL_FORMAT_BayerGB12Packed = 0x010C002C
}HIK_PIXEL_FORMAT;


typedef enum _HIK_IMAGE_COMPRESSION_MODE_ // ImageCompressionMode
{
    HIK_IMAGE_COMPRESSION_MODE_OFF = 0,
    HIK_IMAGE_COMPRESSION_MODE_JPEG = 1,
    HIK_IMAGE_COMPRESSION_MODE_HB = 2,
}HIK_IMAGE_COMPRESSION_MODE;



/*Acquisition Control*/
typedef enum _HIK_ACQUISITION_LINE_RATE_ENABLE_ // AcquisitionLineRateEnable
{
    HIK_ACQUISITION_LINE_RATE_ENABLE_OFF = 0,
    HIK_ACQUISITION_LINE_RATE_ENABLE_ON = 1
}HIK_ACQUISITION_LINE_RATE_ENABLE;


typedef enum _HIK_TRIGGER_MODE_ // TriggerMode
{
    HIK_TRIGGER_MODE_OFF = 0,
    HIK_TRIGGER_MODE_ON = 1 
}HIK_TRIGGER_MODE;


// nRet = HIK_CC_SetEnuhIKalue(handle, "TriggerSource", HIK_Line0);
typedef enum _HIK_TRIGGER_SOURCE_ // TriggerSource
{
    HIK_TRIGGER_SOURCE_Line0 = 0, 
    HIK_TRIGGER_SOURCE_Line1 = 1, 
    HIK_TRIGGER_SOURCE_Line2 = 2,
    HIK_TRIGGER_SOURCE_Line3 = 3,
    HIK_TRIGGER_SOURCE_Counter0 = 4, 
    HIK_TRIGGER_SOURCE_Software = 7,
    HIK_TRIGGER_SOURCE_FrequencyConverter = 8,
    HIK_TRIGGER_SOURCE_Action1_SPECIAL = -1
}HIK_TRIGGER_SOURCE;

// nRet = HIK_CC_SetEnuhIKalueByString(handle, "TriggerSource", HIK_Action1);
#define HIK_TRIGGER_SOURCE_Action1 "Action1"


typedef enum _HIK_TRIGGER_ACTIVATION_ // TriggerActivation
{
    HIK_TRIGGER_ACTIVATION_RisingEdge = 0,
    HIK_TRIGGER_ACTIVATION_FallingEdge = 1,
    HIK_TRIGGER_ACTIVATION_LevelHigh = 2,
    HIK_TRIGGER_ACTIVATION_LevelLow = 3
}HIK_TRIGGER_ACTIVATION;


typedef enum _HIK_EXPOSURE_AUTO_ //ExposureAuto
{
    HIK_EXPOSURE_AUTO_OFF = 0,
    HIK_EXPOSURE_AUTO_ONCE = 1,
    HIK_EXPOSURE_AUTO_CONTINUOUS = 2
}HIK_EXPOSURE_AUTO;


typedef enum _HIK_GAIN_AUTO_ // GainAuto
{
    HIK_GAIN_AUTO_OFF = 0,
    HIK_GAIN_AUTO_ONCE = 1,
    HIK_GAIN_AUTO_CONTINUOUS = 2
}HIK_GAIN_AUTO;



/*Digital IO Control*/
typedef enum _HIK_LINE_SELECTOR_ // LineSelector
{
    HIK_LINE_SELECTOR_Line0 = 0, 
    HIK_LINE_SELECTOR_Line1 = 1, 
    HIK_LINE_SELECTOR_Line2 = 2,
    HIK_LINE_SELECTOR_Line3 = 3,
    HIK_LINE_SELECTOR_Line4 = 4
}HIK_LINE_SELECTOR;


typedef enum _HIK_LINE_MODE_ // LineMode
{
    HIK_LINE_MODE_Input = 0,
    HIK_LINE_MODE_Output = 1,
    HIK_LINE_MODE_Trigger = 2,
    HIK_LINE_MODE_Strobe = 8
}HIK_LINE_MODE;


typedef enum _HIK_LINE_SOURCE_ // LineSource
{
    HIK_LINE_SOURCE_ExposureStartActive = 0,
    HIK_LINE_SOURCE_SoftTriggerActive = 5,
    HIK_LINE_SOURCE_HardTriggerActive = 6
}HIK_LINE_SOURCE;


typedef enum _HIK_STROBE_ENABLE_ //StrobeEnable
{
    HIK_STROBE_ENABLE_OFF = 0,
    HIK_STROBE_ENABLE_ON = 1
}HIK_STROBE_ENABLE;



/*Transport Layer Control*/
typedef enum _HIK_GEV_IEEE_1588_ // GevIEEE1588
{
    HIK_GEV_IEEE_1588_OFF = 0,
    HIK_GEV_IEEE_1588_ON = 1
}HIK_GEV_IEEE_1588;

#endif